version: '3'
services:
  web:
    image: node:8
    ports:
      - 3000:3000
    depends_on:
      - db
    volumes:
      - smokealarm_nodemodules:/usr/src/app/node_modules
      - .:/usr/src/app
    working_dir: /usr/src/app
    environment:
      - NODE_ENV=development
    command: npm run dev
  db:
    image: postgres:12
    ports:
      - 5432:5432
    volumes:
      - smokealarm_postgres:/var/lib/postgresql/data
      - ./migrations/8e970a3-initial-db.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: smokealarm_development
volumes:
  smokealarm_postgres:
    external: true
  smokealarm_nodemodules:
    external: true
